version: "3.7"
services:
  dev_env:
    container_name: my_php8
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu
    image: ubuntu_dev_env:latest
    ports:
      - 80:80
      - 8080-8085:8080-8085
      - 443:443
    volumes: 
      - ./www:/var/www/html
      - ./docker/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/ports.conf:/etc/apache2/ports.conf
      - ./docker/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./docker/logs:/var/log/apache2
      - ./docker/php.ini:/etc/php/8.1/apache2/php.ini
      
    depends_on:
      - mysql
  mysql:
    container_name: my_db_php8
    image: mysql:8.0.26
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password --sql_mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    cap_add:
      - SYS_NICE
    ports: 
      - 3306:3306
      - 33060:33060
    environment: 
      MYSQL_DATABASE: docker_php
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Kolkata
    volumes: 
      - my_db_data:/var/lib/mysql
    networks: 
      - default
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sujay
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo-db:/data/db
    
volumes:
  my_db_data:
  mongo-db: