version: "3.7"
services:
  dev_env:
    container_name: my_php8
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu
    image: ubuntu_dev_env
    ports:
      - 80:80
      - 443:443
      - 8080-8085:8080-8085
    volumes:
      - ./www:/var/www/html
      - ./docker/logs:/var/log/apache2
      # - ./docker/php/php.ini:/etc/
      # - ./docker/apache/apache.conf:/etc/

  mysql:
    container_name: my_db_php8
    image: mysql:8.0.26
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password --sql_mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    cap_add:
      - SYS_NICE
    ports: 
      - 3306:3306
      - 33060:33060
    environment: 
      MYSQL_DATABASE: docker_php
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Kolkata
    volumes:
      - my_db_data:/var/lib/musql
    networks:
      - default

volumes:
  my_db_data:


